{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-directpa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/directPA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/directPA/directPA_{{ version }}.tar.gz
  sha256: ff1dbd1dafd681c8f68008aef88493845d05aefb9490e0c6796e95cf330acf60

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-calibrate
    - r-plotly
  run:
    - r-base
    - r-calibrate
    - r-plotly

test:
  commands:
    - $R -e "library('directPA')"           # [not win]
    - "\"%R%\" -e \"library('directPA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=directPA
  license: GPL-3.0-or-later
  summary: Direction analysis is a set of tools designed to identify combinatorial effects of multiple treatments/conditions on pathways and kinases profiled by microarray, RNA-seq, proteomics, or phosphoproteomics data. See Yang P et al (2014) <doi:10.1093/bioinformatics/btt616>; and Yang P et al. (2016) <doi:10.1002/pmic.201600068>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: directPA
# Type: Package
# Title: Direction Analysis for Pathways and Kinases
# Version: 1.5
# Date: 2020-11-16
# Author: Pengyi Yang & Ellis Patrick
# Maintainer: Pengyi Yang <yangpy7@gmail.com>
# Description: Direction analysis is a set of tools designed to identify combinatorial effects of multiple treatments/conditions on pathways and kinases profiled by microarray, RNA-seq, proteomics, or phosphoproteomics data. See Yang P et al (2014) <doi:10.1093/bioinformatics/btt616>; and Yang P et al. (2016) <doi:10.1002/pmic.201600068>.
# License: GPL-3
# Depends: R (>= 3.10.0),
# Imports: grDevices, graphics, stats, plotly, calibrate
# Packaged: 2020-11-15 23:10:25 UTC; pengyi
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2020-11-16 05:10:02 UTC
# RoxygenNote: 7.1.1
